---
version: "2.4"
services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1502
      - PGID=1502
      - MEM_LIMIT=1024M #optional
    volumes:
      - mnt/sharedata/unifi/data:/config
    restart: unless-stopped
    networks:
      unifi:
        ipv4_address: 10.10.1.28

networks:
  unifi:
    driver: macvlan
    driver_opts:
      parent: eth1
    ipam:
      config:
        - subnet: "10.10.1.0/26"
          ip_range: "10.10.1.28/32"
          gateway: "10.10.1.1"
